[package]
name = "osu-map-analyzer"
version = "0.2.9"
authors = ["yorunoken <me@yorunoken.com>"]
edition = "2021"
description = "A library and CLI for analyzing osu! beatmaps"
repository = "https://github.com/yorunoken/osu-map-analyzer-lib"
documentation = "https://docs.rs/osu-map-analyzer"
license = "Apache-2.0"
readme = "README.md"
keywords = ["osu", "beatmap", "analysis"]
categories = ["games", "command-line-utilities"]

[dependencies]
rosu-map = "0.1.2"
rosu-pp = "4.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", optional = true }

[features]
default = ["serialize"]
serialize = ["dep:serde_json"]
